### ISSUE TITLE
onfleet not registered with npm

### ISSUE THREAD

**Issue by mjk** [trusk-official/onfleet-node#6]
Hi there! Is there any reason you haven't run `npm publish` yet? I was going to create my own Onfleet wrapper, but when I found this, I figured I'd rather build on top of it.

**Comment by jonathanasquier** [comment]
hum... because I'm lazy I think. Right now I'm doing
```
"onfleet": "git+https://github.com/trusk-official/onfleet-node.git#2.0.0"
```
in my package.json.
I'll go ahead and publish on npm.

**Comment by jonathanasquier** [comment]
And voila!
https://www.npmjs.com/package/onfleet

**Comment by mjk** [comment]
Hurrah!
