### ISSUE TITLE
Fetch Authentification

### ISSUE THREAD

**Issue by huynhdoo** [trusk-official/onfleet-node#8]
Hi,

Thanks for your great work !

In your modules/fetch.js file, it seems that the authentification in the url (_https://key@onfleet.com/api/v2/_) doesn't work on some case.

I can fix the issue with: 
**1. Putting the authentification in the fetch call:**
```
fetch(url, {
    method: params.method,
    headers: params.headers || {
      'Authorization': "Basic " + window.btoa(key),
      'Accept': 'application/json',
      'Content-Type': 'application/json'},
    body,
 })
```

**2. Remove the authentification key from the url:**
`const url = `${protocol}://${params.host}${port}${basePath}${version}${params.path}${queryString}`;`

What do you think about this code changes?

Best,

Do Huynh

**Comment by jonathanasquier** [comment]
Hi @huynhdoo, and thank you for your message!
feel free to provide a PR with your changes :)
If you had a process that would enable us to easily test the failing case, and the working case on the PR it would be purrrfect!

**Comment by jonathanasquier** [comment]
please transition to https://github.com/onfleet/node-onfleet
